version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=900
      - PGID=900
      - TZ=America/Argentina/Buenos_Aires
      - SERVERPORT=51820 
      - PEERS=1 #cantidad de clientes
      - INTERNAL_SUBNET=10.13.13.0 #subred
    volumes:
      - $HOME/wireguard-server/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always